<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>chipeightasm</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ChipEight.Assembler\ChipEight.Assembler.csproj" />
    </ItemGroup>

</Project>
